//SignUp

export const FETCH_SIGNUP_SUCCESS = "FETCH_SIGNUP_SUCCESS";
export const FETCH_SIGNUP_ERROR = "FETCH_SIGNUP_ERROR";

//LogIn

export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_ERROR = "FETCH_LOGIN_ERROR";
export const FETCH_LOGOUT_SUCCESS = "FETCH_LOGOUT_SUCCESS";
